apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xserviceaccounts.gcp.test.upbound.io
spec:
  group: gcp.test.upbound.io
  names:
    kind: XServiceAccount
    plural: xserviceaccounts
  claimNames:
    kind: ServiceAccount
    plural: serviceaccounts
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              serviceAccountName:
                type: string
                description: Name of the IAM service account.
            required:
            - serviceAccountName
