apiVersion: gcp.test.upbound.io/v1alpha1
kind: ServiceAccount
metadata:
  name: migration-test
  namespace: default
spec:
  serviceAccountName: alper-migration-test
  resourceGroupName: alper-migration-test
  writeConnectionSecretToRef:
    name: migration-test-conn
