apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-migration-test
  annotations:
    meta.crossplane.io/source: github.com/ulucinar/alper-test-configuration
spec:
  crossplane:
    version: ">=v1.12.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp
      version: "v0.32.0"
